name: moviereminder-ci
on:
  pull_request:
    branches:
      - "master"
jobs:
  moviereminder-test:
    name: Test JS
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: MovieReminder
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install packages
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.PROJECT_PATH }}
      - name: Test
        run: yarn run test
        working-directory: ${{ env.PROJECT_PATH }}
